/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AggTrade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class AggTrade {
  @SerializedName("a")
  private Integer a = null;

  @SerializedName("p")
  private String p = null;

  @SerializedName("q")
  private String q = null;

  @SerializedName("f")
  private Integer f = null;

  @SerializedName("l")
  private Integer l = null;

  @SerializedName("T")
  private Boolean T = null;

  @SerializedName("m")
  private Boolean m = null;

  @SerializedName("M")
  private Boolean M = null;

  public AggTrade a(Integer a) {
    this.a = a;
    return this;
  }

   /**
   * trade id
   * @return a
  **/
  @Schema(example = "345196462", description = "trade id")
  public Integer getA() {
    return a;
  }

  public void setA(Integer a) {
    this.a = a;
  }

  public AggTrade p(String p) {
    this.p = p;
    return this;
  }

   /**
   * price
   * @return p
  **/
  @Schema(example = "9638.99000000", description = "price")
  public String getP() {
    return p;
  }

  public void setP(String p) {
    this.p = p;
  }

  public AggTrade q(String q) {
    this.q = q;
    return this;
  }

   /**
   * amount of base asset
   * @return q
  **/
  @Schema(example = "0.02077200", description = "amount of base asset")
  public String getQ() {
    return q;
  }

  public void setQ(String q) {
    this.q = q;
  }

  public AggTrade f(Integer f) {
    this.f = f;
    return this;
  }

   /**
   * First tradeId
   * @return f
  **/
  @Schema(example = "345212431", description = "First tradeId")
  public Integer getF() {
    return f;
  }

  public void setF(Integer f) {
    this.f = f;
  }

  public AggTrade l(Integer l) {
    this.l = l;
    return this;
  }

   /**
   * Last tradeId
   * @return l
  **/
  @Schema(example = "345212431", description = "Last tradeId")
  public Integer getL() {
    return l;
  }

  public void setL(Integer l) {
    this.l = l;
  }

  public AggTrade T(Boolean T) {
    this.T = T;
    return this;
  }

   /**
   * Timestamp
   * @return T
  **/
  @Schema(example = "false", description = "Timestamp")
  public Boolean isT() {
    return T;
  }

  public void setT(Boolean T) {
    this.T = T;
  }

  public AggTrade m(Boolean m) {
    this.m = m;
    return this;
  }

   /**
   * Was the buyer the maker?
   * @return m
  **/
  @Schema(example = "true", description = "Was the buyer the maker?")
  public Boolean isM() {
    return m;
  }

  public void setM(Boolean m) {
    this.m = m;
  }

  public AggTrade M(Boolean M) {
    this.M = M;
    return this;
  }

   /**
   * Was the trade the best price match?
   * @return M
  **/
  @Schema(example = "true", description = "Was the trade the best price match?")
  public Boolean isM() {
    return M;
  }

  public void setM(Boolean M) {
    this.M = M;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggTrade aggTrade = (AggTrade) o;
    return Objects.equals(this.a, aggTrade.a) &&
        Objects.equals(this.p, aggTrade.p) &&
        Objects.equals(this.q, aggTrade.q) &&
        Objects.equals(this.f, aggTrade.f) &&
        Objects.equals(this.l, aggTrade.l) &&
        Objects.equals(this.T, aggTrade.T) &&
        Objects.equals(this.m, aggTrade.m) &&
        Objects.equals(this.M, aggTrade.M);
  }

  @Override
  public int hashCode() {
    return Objects.hash(a, p, q, f, l, T, m, M);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggTrade {\n");
    
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    p: ").append(toIndentedString(p)).append("\n");
    sb.append("    q: ").append(toIndentedString(q)).append("\n");
    sb.append("    f: ").append(toIndentedString(f)).append("\n");
    sb.append("    l: ").append(toIndentedString(l)).append("\n");
    sb.append("    T: ").append(toIndentedString(T)).append("\n");
    sb.append("    m: ").append(toIndentedString(m)).append("\n");
    sb.append("    M: ").append(toIndentedString(M)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
