/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20030TradeFee
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20030TradeFee {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("maker")
  private Integer maker = null;

  @SerializedName("taker")
  private Integer taker = null;

  public InlineResponse20030TradeFee symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "ADABNB", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public InlineResponse20030TradeFee maker(Integer maker) {
    this.maker = maker;
    return this;
  }

   /**
   * Get maker
   * @return maker
  **/
  @Schema(description = "")
  public Integer getMaker() {
    return maker;
  }

  public void setMaker(Integer maker) {
    this.maker = maker;
  }

  public InlineResponse20030TradeFee taker(Integer taker) {
    this.taker = taker;
    return this;
  }

   /**
   * Get taker
   * @return taker
  **/
  @Schema(example = "1", description = "")
  public Integer getTaker() {
    return taker;
  }

  public void setTaker(Integer taker) {
    this.taker = taker;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20030TradeFee inlineResponse20030TradeFee = (InlineResponse20030TradeFee) o;
    return Objects.equals(this.symbol, inlineResponse20030TradeFee.symbol) &&
        Objects.equals(this.maker, inlineResponse20030TradeFee.maker) &&
        Objects.equals(this.taker, inlineResponse20030TradeFee.taker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, maker, taker);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20030TradeFee {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    maker: ").append(toIndentedString(maker)).append("\n");
    sb.append("    taker: ").append(toIndentedString(taker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
