/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20017UserAssets
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20017UserAssets {
  @SerializedName("asset")
  private String asset = null;

  @SerializedName("borrowed")
  private String borrowed = null;

  @SerializedName("free")
  private String free = null;

  @SerializedName("interest")
  private String interest = null;

  @SerializedName("locked")
  private String locked = null;

  @SerializedName("netAsset")
  private String netAsset = null;

  public InlineResponse20017UserAssets asset(String asset) {
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @Schema(example = "BTC", description = "")
  public String getAsset() {
    return asset;
  }

  public void setAsset(String asset) {
    this.asset = asset;
  }

  public InlineResponse20017UserAssets borrowed(String borrowed) {
    this.borrowed = borrowed;
    return this;
  }

   /**
   * Get borrowed
   * @return borrowed
  **/
  @Schema(example = "0.00000000", description = "")
  public String getBorrowed() {
    return borrowed;
  }

  public void setBorrowed(String borrowed) {
    this.borrowed = borrowed;
  }

  public InlineResponse20017UserAssets free(String free) {
    this.free = free;
    return this;
  }

   /**
   * Get free
   * @return free
  **/
  @Schema(example = "0.00499500", description = "")
  public String getFree() {
    return free;
  }

  public void setFree(String free) {
    this.free = free;
  }

  public InlineResponse20017UserAssets interest(String interest) {
    this.interest = interest;
    return this;
  }

   /**
   * Get interest
   * @return interest
  **/
  @Schema(example = "0.00000000", description = "")
  public String getInterest() {
    return interest;
  }

  public void setInterest(String interest) {
    this.interest = interest;
  }

  public InlineResponse20017UserAssets locked(String locked) {
    this.locked = locked;
    return this;
  }

   /**
   * Get locked
   * @return locked
  **/
  @Schema(example = "0.00000000", description = "")
  public String getLocked() {
    return locked;
  }

  public void setLocked(String locked) {
    this.locked = locked;
  }

  public InlineResponse20017UserAssets netAsset(String netAsset) {
    this.netAsset = netAsset;
    return this;
  }

   /**
   * Get netAsset
   * @return netAsset
  **/
  @Schema(example = "0.00499500", description = "")
  public String getNetAsset() {
    return netAsset;
  }

  public void setNetAsset(String netAsset) {
    this.netAsset = netAsset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017UserAssets inlineResponse20017UserAssets = (InlineResponse20017UserAssets) o;
    return Objects.equals(this.asset, inlineResponse20017UserAssets.asset) &&
        Objects.equals(this.borrowed, inlineResponse20017UserAssets.borrowed) &&
        Objects.equals(this.free, inlineResponse20017UserAssets.free) &&
        Objects.equals(this.interest, inlineResponse20017UserAssets.interest) &&
        Objects.equals(this.locked, inlineResponse20017UserAssets.locked) &&
        Objects.equals(this.netAsset, inlineResponse20017UserAssets.netAsset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asset, borrowed, free, interest, locked, netAsset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017UserAssets {\n");
    
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    borrowed: ").append(toIndentedString(borrowed)).append("\n");
    sb.append("    free: ").append(toIndentedString(free)).append("\n");
    sb.append("    interest: ").append(toIndentedString(interest)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    netAsset: ").append(toIndentedString(netAsset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
