/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2001RateLimits
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse2001RateLimits {
  @SerializedName("rateLimitType")
  private String rateLimitType = null;

  @SerializedName("interval")
  private String interval = null;

  @SerializedName("intervalNum")
  private Integer intervalNum = null;

  @SerializedName("limit")
  private Integer limit = null;

  public InlineResponse2001RateLimits rateLimitType(String rateLimitType) {
    this.rateLimitType = rateLimitType;
    return this;
  }

   /**
   * Get rateLimitType
   * @return rateLimitType
  **/
  @Schema(example = "REQUEST_WEIGHT", description = "")
  public String getRateLimitType() {
    return rateLimitType;
  }

  public void setRateLimitType(String rateLimitType) {
    this.rateLimitType = rateLimitType;
  }

  public InlineResponse2001RateLimits interval(String interval) {
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  @Schema(example = "MINUTE", description = "")
  public String getInterval() {
    return interval;
  }

  public void setInterval(String interval) {
    this.interval = interval;
  }

  public InlineResponse2001RateLimits intervalNum(Integer intervalNum) {
    this.intervalNum = intervalNum;
    return this;
  }

   /**
   * Get intervalNum
   * @return intervalNum
  **/
  @Schema(example = "1", description = "")
  public Integer getIntervalNum() {
    return intervalNum;
  }

  public void setIntervalNum(Integer intervalNum) {
    this.intervalNum = intervalNum;
  }

  public InlineResponse2001RateLimits limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @Schema(example = "1200", description = "")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001RateLimits inlineResponse2001RateLimits = (InlineResponse2001RateLimits) o;
    return Objects.equals(this.rateLimitType, inlineResponse2001RateLimits.rateLimitType) &&
        Objects.equals(this.interval, inlineResponse2001RateLimits.interval) &&
        Objects.equals(this.intervalNum, inlineResponse2001RateLimits.intervalNum) &&
        Objects.equals(this.limit, inlineResponse2001RateLimits.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rateLimitType, interval, intervalNum, limit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001RateLimits {\n");
    
    sb.append("    rateLimitType: ").append(toIndentedString(rateLimitType)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    intervalNum: ").append(toIndentedString(intervalNum)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
