/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20026ResultsLogs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20026ResultsLogs {
  @SerializedName("tranId")
  private Integer tranId = null;

  @SerializedName("serviceChargeAmount")
  private String serviceChargeAmount = null;

  @SerializedName("uid")
  private String uid = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("operateTime")
  private String operateTime = null;

  @SerializedName("transferedAmount")
  private String transferedAmount = null;

  @SerializedName("fromAsset")
  private String fromAsset = null;

  public InlineResponse20026ResultsLogs tranId(Integer tranId) {
    this.tranId = tranId;
    return this;
  }

   /**
   * Get tranId
   * @return tranId
  **/
  @Schema(example = "4359321", description = "")
  public Integer getTranId() {
    return tranId;
  }

  public void setTranId(Integer tranId) {
    this.tranId = tranId;
  }

  public InlineResponse20026ResultsLogs serviceChargeAmount(String serviceChargeAmount) {
    this.serviceChargeAmount = serviceChargeAmount;
    return this;
  }

   /**
   * Get serviceChargeAmount
   * @return serviceChargeAmount
  **/
  @Schema(example = "0.000009", description = "")
  public String getServiceChargeAmount() {
    return serviceChargeAmount;
  }

  public void setServiceChargeAmount(String serviceChargeAmount) {
    this.serviceChargeAmount = serviceChargeAmount;
  }

  public InlineResponse20026ResultsLogs uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(example = "10000015", description = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public InlineResponse20026ResultsLogs amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(example = "0.0009", description = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public InlineResponse20026ResultsLogs operateTime(String operateTime) {
    this.operateTime = operateTime;
    return this;
  }

   /**
   * Get operateTime
   * @return operateTime
  **/
  @Schema(example = "2018-05-03 17:07:04", description = "")
  public String getOperateTime() {
    return operateTime;
  }

  public void setOperateTime(String operateTime) {
    this.operateTime = operateTime;
  }

  public InlineResponse20026ResultsLogs transferedAmount(String transferedAmount) {
    this.transferedAmount = transferedAmount;
    return this;
  }

   /**
   * Get transferedAmount
   * @return transferedAmount
  **/
  @Schema(example = "0.000441", description = "")
  public String getTransferedAmount() {
    return transferedAmount;
  }

  public void setTransferedAmount(String transferedAmount) {
    this.transferedAmount = transferedAmount;
  }

  public InlineResponse20026ResultsLogs fromAsset(String fromAsset) {
    this.fromAsset = fromAsset;
    return this;
  }

   /**
   * Get fromAsset
   * @return fromAsset
  **/
  @Schema(example = "USDT", description = "")
  public String getFromAsset() {
    return fromAsset;
  }

  public void setFromAsset(String fromAsset) {
    this.fromAsset = fromAsset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20026ResultsLogs inlineResponse20026ResultsLogs = (InlineResponse20026ResultsLogs) o;
    return Objects.equals(this.tranId, inlineResponse20026ResultsLogs.tranId) &&
        Objects.equals(this.serviceChargeAmount, inlineResponse20026ResultsLogs.serviceChargeAmount) &&
        Objects.equals(this.uid, inlineResponse20026ResultsLogs.uid) &&
        Objects.equals(this.amount, inlineResponse20026ResultsLogs.amount) &&
        Objects.equals(this.operateTime, inlineResponse20026ResultsLogs.operateTime) &&
        Objects.equals(this.transferedAmount, inlineResponse20026ResultsLogs.transferedAmount) &&
        Objects.equals(this.fromAsset, inlineResponse20026ResultsLogs.fromAsset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tranId, serviceChargeAmount, uid, amount, operateTime, transferedAmount, fromAsset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20026ResultsLogs {\n");
    
    sb.append("    tranId: ").append(toIndentedString(tranId)).append("\n");
    sb.append("    serviceChargeAmount: ").append(toIndentedString(serviceChargeAmount)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    operateTime: ").append(toIndentedString(operateTime)).append("\n");
    sb.append("    transferedAmount: ").append(toIndentedString(transferedAmount)).append("\n");
    sb.append("    fromAsset: ").append(toIndentedString(fromAsset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
