/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20012
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20012 {
  @SerializedName("assetFullName")
  private String assetFullName = null;

  @SerializedName("assetName")
  private String assetName = null;

  @SerializedName("isBorrowable")
  private Boolean isBorrowable = null;

  @SerializedName("isMortgageable")
  private Boolean isMortgageable = null;

  @SerializedName("userMinBorrow")
  private String userMinBorrow = null;

  @SerializedName("userMinRepay")
  private String userMinRepay = null;

  public InlineResponse20012 assetFullName(String assetFullName) {
    this.assetFullName = assetFullName;
    return this;
  }

   /**
   * Get assetFullName
   * @return assetFullName
  **/
  @Schema(example = "Binance coin", description = "")
  public String getAssetFullName() {
    return assetFullName;
  }

  public void setAssetFullName(String assetFullName) {
    this.assetFullName = assetFullName;
  }

  public InlineResponse20012 assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Get assetName
   * @return assetName
  **/
  @Schema(example = "BNB", description = "")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public InlineResponse20012 isBorrowable(Boolean isBorrowable) {
    this.isBorrowable = isBorrowable;
    return this;
  }

   /**
   * Get isBorrowable
   * @return isBorrowable
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsBorrowable() {
    return isBorrowable;
  }

  public void setIsBorrowable(Boolean isBorrowable) {
    this.isBorrowable = isBorrowable;
  }

  public InlineResponse20012 isMortgageable(Boolean isMortgageable) {
    this.isMortgageable = isMortgageable;
    return this;
  }

   /**
   * Get isMortgageable
   * @return isMortgageable
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsMortgageable() {
    return isMortgageable;
  }

  public void setIsMortgageable(Boolean isMortgageable) {
    this.isMortgageable = isMortgageable;
  }

  public InlineResponse20012 userMinBorrow(String userMinBorrow) {
    this.userMinBorrow = userMinBorrow;
    return this;
  }

   /**
   * Get userMinBorrow
   * @return userMinBorrow
  **/
  @Schema(example = "0.00000000", description = "")
  public String getUserMinBorrow() {
    return userMinBorrow;
  }

  public void setUserMinBorrow(String userMinBorrow) {
    this.userMinBorrow = userMinBorrow;
  }

  public InlineResponse20012 userMinRepay(String userMinRepay) {
    this.userMinRepay = userMinRepay;
    return this;
  }

   /**
   * Get userMinRepay
   * @return userMinRepay
  **/
  @Schema(example = "0.00000000", description = "")
  public String getUserMinRepay() {
    return userMinRepay;
  }

  public void setUserMinRepay(String userMinRepay) {
    this.userMinRepay = userMinRepay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012 inlineResponse20012 = (InlineResponse20012) o;
    return Objects.equals(this.assetFullName, inlineResponse20012.assetFullName) &&
        Objects.equals(this.assetName, inlineResponse20012.assetName) &&
        Objects.equals(this.isBorrowable, inlineResponse20012.isBorrowable) &&
        Objects.equals(this.isMortgageable, inlineResponse20012.isMortgageable) &&
        Objects.equals(this.userMinBorrow, inlineResponse20012.userMinBorrow) &&
        Objects.equals(this.userMinRepay, inlineResponse20012.userMinRepay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetFullName, assetName, isBorrowable, isMortgageable, userMinBorrow, userMinRepay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012 {\n");
    
    sb.append("    assetFullName: ").append(toIndentedString(assetFullName)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    isBorrowable: ").append(toIndentedString(isBorrowable)).append("\n");
    sb.append("    isMortgageable: ").append(toIndentedString(isMortgageable)).append("\n");
    sb.append("    userMinBorrow: ").append(toIndentedString(userMinBorrow)).append("\n");
    sb.append("    userMinRepay: ").append(toIndentedString(userMinRepay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
