/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20028Rows
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20028Rows {
  @SerializedName("amount")
  private String amount = null;

  @SerializedName("asset")
  private String asset = null;

  @SerializedName("divTime")
  private Integer divTime = null;

  @SerializedName("enInfo")
  private String enInfo = null;

  @SerializedName("tranId")
  private Integer tranId = null;

  public InlineResponse20028Rows amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(example = "10.00000000", description = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public InlineResponse20028Rows asset(String asset) {
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @Schema(example = "BHFT", description = "")
  public String getAsset() {
    return asset;
  }

  public void setAsset(String asset) {
    this.asset = asset;
  }

  public InlineResponse20028Rows divTime(Integer divTime) {
    this.divTime = divTime;
    return this;
  }

   /**
   * Get divTime
   * @return divTime
  **/
  @Schema(example = "1563189166000", description = "")
  public Integer getDivTime() {
    return divTime;
  }

  public void setDivTime(Integer divTime) {
    this.divTime = divTime;
  }

  public InlineResponse20028Rows enInfo(String enInfo) {
    this.enInfo = enInfo;
    return this;
  }

   /**
   * Get enInfo
   * @return enInfo
  **/
  @Schema(example = "BHFT distribution", description = "")
  public String getEnInfo() {
    return enInfo;
  }

  public void setEnInfo(String enInfo) {
    this.enInfo = enInfo;
  }

  public InlineResponse20028Rows tranId(Integer tranId) {
    this.tranId = tranId;
    return this;
  }

   /**
   * Get tranId
   * @return tranId
  **/
  @Schema(example = "2968885920", description = "")
  public Integer getTranId() {
    return tranId;
  }

  public void setTranId(Integer tranId) {
    this.tranId = tranId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20028Rows inlineResponse20028Rows = (InlineResponse20028Rows) o;
    return Objects.equals(this.amount, inlineResponse20028Rows.amount) &&
        Objects.equals(this.asset, inlineResponse20028Rows.asset) &&
        Objects.equals(this.divTime, inlineResponse20028Rows.divTime) &&
        Objects.equals(this.enInfo, inlineResponse20028Rows.enInfo) &&
        Objects.equals(this.tranId, inlineResponse20028Rows.tranId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, asset, divTime, enInfo, tranId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20028Rows {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    divTime: ").append(toIndentedString(divTime)).append("\n");
    sb.append("    enInfo: ").append(toIndentedString(enInfo)).append("\n");
    sb.append("    tranId: ").append(toIndentedString(tranId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
