/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20025StatusIndicators;
import io.swagger.client.model.InlineResponse20025StatusTriggerCondition;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20025Status
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20025Status {
  @SerializedName("isLocked")
  private Boolean isLocked = null;

  @SerializedName("plannedRecoverTime")
  private Integer plannedRecoverTime = null;

  @SerializedName("triggerCondition")
  private InlineResponse20025StatusTriggerCondition triggerCondition = null;

  @SerializedName("indicators")
  private InlineResponse20025StatusIndicators indicators = null;

  @SerializedName("updateTime")
  private Integer updateTime = null;

  public InlineResponse20025Status isLocked(Boolean isLocked) {
    this.isLocked = isLocked;
    return this;
  }

   /**
   * Get isLocked
   * @return isLocked
  **/
  @Schema(example = "false", description = "")
  public Boolean isIsLocked() {
    return isLocked;
  }

  public void setIsLocked(Boolean isLocked) {
    this.isLocked = isLocked;
  }

  public InlineResponse20025Status plannedRecoverTime(Integer plannedRecoverTime) {
    this.plannedRecoverTime = plannedRecoverTime;
    return this;
  }

   /**
   * Get plannedRecoverTime
   * @return plannedRecoverTime
  **/
  @Schema(example = "0", description = "")
  public Integer getPlannedRecoverTime() {
    return plannedRecoverTime;
  }

  public void setPlannedRecoverTime(Integer plannedRecoverTime) {
    this.plannedRecoverTime = plannedRecoverTime;
  }

  public InlineResponse20025Status triggerCondition(InlineResponse20025StatusTriggerCondition triggerCondition) {
    this.triggerCondition = triggerCondition;
    return this;
  }

   /**
   * Get triggerCondition
   * @return triggerCondition
  **/
  @Schema(description = "")
  public InlineResponse20025StatusTriggerCondition getTriggerCondition() {
    return triggerCondition;
  }

  public void setTriggerCondition(InlineResponse20025StatusTriggerCondition triggerCondition) {
    this.triggerCondition = triggerCondition;
  }

  public InlineResponse20025Status indicators(InlineResponse20025StatusIndicators indicators) {
    this.indicators = indicators;
    return this;
  }

   /**
   * Get indicators
   * @return indicators
  **/
  @Schema(description = "")
  public InlineResponse20025StatusIndicators getIndicators() {
    return indicators;
  }

  public void setIndicators(InlineResponse20025StatusIndicators indicators) {
    this.indicators = indicators;
  }

  public InlineResponse20025Status updateTime(Integer updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @Schema(example = "1593500803840", description = "")
  public Integer getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(Integer updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20025Status inlineResponse20025Status = (InlineResponse20025Status) o;
    return Objects.equals(this.isLocked, inlineResponse20025Status.isLocked) &&
        Objects.equals(this.plannedRecoverTime, inlineResponse20025Status.plannedRecoverTime) &&
        Objects.equals(this.triggerCondition, inlineResponse20025Status.triggerCondition) &&
        Objects.equals(this.indicators, inlineResponse20025Status.indicators) &&
        Objects.equals(this.updateTime, inlineResponse20025Status.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isLocked, plannedRecoverTime, triggerCondition, indicators, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20025Status {\n");
    
    sb.append("    isLocked: ").append(toIndentedString(isLocked)).append("\n");
    sb.append("    plannedRecoverTime: ").append(toIndentedString(plannedRecoverTime)).append("\n");
    sb.append("    triggerCondition: ").append(toIndentedString(triggerCondition)).append("\n");
    sb.append("    indicators: ").append(toIndentedString(indicators)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
