/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse2008OrderReports;
import io.swagger.client.model.InlineResponse2008Orders;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2008
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse2008 {
  @SerializedName("orderListId")
  private Integer orderListId = null;

  @SerializedName("contingencyType")
  private String contingencyType = null;

  @SerializedName("listStatusType")
  private String listStatusType = null;

  @SerializedName("listOrderStatus")
  private String listOrderStatus = null;

  @SerializedName("listClientOrderId")
  private String listClientOrderId = null;

  @SerializedName("transactionTime")
  private Integer transactionTime = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("orders")
  private List<InlineResponse2008Orders> orders = null;

  @SerializedName("orderReports")
  private List<InlineResponse2008OrderReports> orderReports = null;

  public InlineResponse2008 orderListId(Integer orderListId) {
    this.orderListId = orderListId;
    return this;
  }

   /**
   * Get orderListId
   * @return orderListId
  **/
  @Schema(example = "0", description = "")
  public Integer getOrderListId() {
    return orderListId;
  }

  public void setOrderListId(Integer orderListId) {
    this.orderListId = orderListId;
  }

  public InlineResponse2008 contingencyType(String contingencyType) {
    this.contingencyType = contingencyType;
    return this;
  }

   /**
   * Get contingencyType
   * @return contingencyType
  **/
  @Schema(example = "OCO", description = "")
  public String getContingencyType() {
    return contingencyType;
  }

  public void setContingencyType(String contingencyType) {
    this.contingencyType = contingencyType;
  }

  public InlineResponse2008 listStatusType(String listStatusType) {
    this.listStatusType = listStatusType;
    return this;
  }

   /**
   * Get listStatusType
   * @return listStatusType
  **/
  @Schema(example = "EXEC_STARTED", description = "")
  public String getListStatusType() {
    return listStatusType;
  }

  public void setListStatusType(String listStatusType) {
    this.listStatusType = listStatusType;
  }

  public InlineResponse2008 listOrderStatus(String listOrderStatus) {
    this.listOrderStatus = listOrderStatus;
    return this;
  }

   /**
   * Get listOrderStatus
   * @return listOrderStatus
  **/
  @Schema(example = "EXECUTING", description = "")
  public String getListOrderStatus() {
    return listOrderStatus;
  }

  public void setListOrderStatus(String listOrderStatus) {
    this.listOrderStatus = listOrderStatus;
  }

  public InlineResponse2008 listClientOrderId(String listClientOrderId) {
    this.listClientOrderId = listClientOrderId;
    return this;
  }

   /**
   * Get listClientOrderId
   * @return listClientOrderId
  **/
  @Schema(example = "JYVpp3F0f5CAG15DhtrqLp", description = "")
  public String getListClientOrderId() {
    return listClientOrderId;
  }

  public void setListClientOrderId(String listClientOrderId) {
    this.listClientOrderId = listClientOrderId;
  }

  public InlineResponse2008 transactionTime(Integer transactionTime) {
    this.transactionTime = transactionTime;
    return this;
  }

   /**
   * Get transactionTime
   * @return transactionTime
  **/
  @Schema(example = "1563417480525", description = "")
  public Integer getTransactionTime() {
    return transactionTime;
  }

  public void setTransactionTime(Integer transactionTime) {
    this.transactionTime = transactionTime;
  }

  public InlineResponse2008 symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "LTCBTC", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public InlineResponse2008 orders(List<InlineResponse2008Orders> orders) {
    this.orders = orders;
    return this;
  }

  public InlineResponse2008 addOrdersItem(InlineResponse2008Orders ordersItem) {
    if (this.orders == null) {
      this.orders = new ArrayList<InlineResponse2008Orders>();
    }
    this.orders.add(ordersItem);
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  @Schema(description = "")
  public List<InlineResponse2008Orders> getOrders() {
    return orders;
  }

  public void setOrders(List<InlineResponse2008Orders> orders) {
    this.orders = orders;
  }

  public InlineResponse2008 orderReports(List<InlineResponse2008OrderReports> orderReports) {
    this.orderReports = orderReports;
    return this;
  }

  public InlineResponse2008 addOrderReportsItem(InlineResponse2008OrderReports orderReportsItem) {
    if (this.orderReports == null) {
      this.orderReports = new ArrayList<InlineResponse2008OrderReports>();
    }
    this.orderReports.add(orderReportsItem);
    return this;
  }

   /**
   * Get orderReports
   * @return orderReports
  **/
  @Schema(description = "")
  public List<InlineResponse2008OrderReports> getOrderReports() {
    return orderReports;
  }

  public void setOrderReports(List<InlineResponse2008OrderReports> orderReports) {
    this.orderReports = orderReports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2008 inlineResponse2008 = (InlineResponse2008) o;
    return Objects.equals(this.orderListId, inlineResponse2008.orderListId) &&
        Objects.equals(this.contingencyType, inlineResponse2008.contingencyType) &&
        Objects.equals(this.listStatusType, inlineResponse2008.listStatusType) &&
        Objects.equals(this.listOrderStatus, inlineResponse2008.listOrderStatus) &&
        Objects.equals(this.listClientOrderId, inlineResponse2008.listClientOrderId) &&
        Objects.equals(this.transactionTime, inlineResponse2008.transactionTime) &&
        Objects.equals(this.symbol, inlineResponse2008.symbol) &&
        Objects.equals(this.orders, inlineResponse2008.orders) &&
        Objects.equals(this.orderReports, inlineResponse2008.orderReports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderListId, contingencyType, listStatusType, listOrderStatus, listClientOrderId, transactionTime, symbol, orders, orderReports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2008 {\n");
    
    sb.append("    orderListId: ").append(toIndentedString(orderListId)).append("\n");
    sb.append("    contingencyType: ").append(toIndentedString(contingencyType)).append("\n");
    sb.append("    listStatusType: ").append(toIndentedString(listStatusType)).append("\n");
    sb.append("    listOrderStatus: ").append(toIndentedString(listOrderStatus)).append("\n");
    sb.append("    listClientOrderId: ").append(toIndentedString(listClientOrderId)).append("\n");
    sb.append("    transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    orderReports: ").append(toIndentedString(orderReports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
