/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20025StatusIndicatorsBTCUSDT
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20025StatusIndicatorsBTCUSDT {
  @SerializedName("i")
  private String i = null;

  @SerializedName("c")
  private Integer c = null;

  @SerializedName("v")
  private Float v = null;

  @SerializedName("t")
  private Float t = null;

  public InlineResponse20025StatusIndicatorsBTCUSDT i(String i) {
    this.i = i;
    return this;
  }

   /**
   * Get i
   * @return i
  **/
  @Schema(example = "UFR", description = "")
  public String getI() {
    return i;
  }

  public void setI(String i) {
    this.i = i;
  }

  public InlineResponse20025StatusIndicatorsBTCUSDT c(Integer c) {
    this.c = c;
    return this;
  }

   /**
   * Get c
   * @return c
  **/
  @Schema(example = "20", description = "")
  public Integer getC() {
    return c;
  }

  public void setC(Integer c) {
    this.c = c;
  }

  public InlineResponse20025StatusIndicatorsBTCUSDT v(Float v) {
    this.v = v;
    return this;
  }

   /**
   * Get v
   * @return v
  **/
  @Schema(example = "20", description = "")
  public Float getV() {
    return v;
  }

  public void setV(Float v) {
    this.v = v;
  }

  public InlineResponse20025StatusIndicatorsBTCUSDT t(Float t) {
    this.t = t;
    return this;
  }

   /**
   * Get t
   * @return t
  **/
  @Schema(example = "20", description = "")
  public Float getT() {
    return t;
  }

  public void setT(Float t) {
    this.t = t;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20025StatusIndicatorsBTCUSDT inlineResponse20025StatusIndicatorsBTCUSDT = (InlineResponse20025StatusIndicatorsBTCUSDT) o;
    return Objects.equals(this.i, inlineResponse20025StatusIndicatorsBTCUSDT.i) &&
        Objects.equals(this.c, inlineResponse20025StatusIndicatorsBTCUSDT.c) &&
        Objects.equals(this.v, inlineResponse20025StatusIndicatorsBTCUSDT.v) &&
        Objects.equals(this.t, inlineResponse20025StatusIndicatorsBTCUSDT.t);
  }

  @Override
  public int hashCode() {
    return Objects.hash(i, c, v, t);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20025StatusIndicatorsBTCUSDT {\n");
    
    sb.append("    i: ").append(toIndentedString(i)).append("\n");
    sb.append("    c: ").append(toIndentedString(c)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
