/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20019DataBalances;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20019Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20019Data {
  @SerializedName("balances")
  private List<InlineResponse20019DataBalances> balances = null;

  @SerializedName("totalAssetOfBtc")
  private String totalAssetOfBtc = null;

  public InlineResponse20019Data balances(List<InlineResponse20019DataBalances> balances) {
    this.balances = balances;
    return this;
  }

  public InlineResponse20019Data addBalancesItem(InlineResponse20019DataBalances balancesItem) {
    if (this.balances == null) {
      this.balances = new ArrayList<InlineResponse20019DataBalances>();
    }
    this.balances.add(balancesItem);
    return this;
  }

   /**
   * Get balances
   * @return balances
  **/
  @Schema(description = "")
  public List<InlineResponse20019DataBalances> getBalances() {
    return balances;
  }

  public void setBalances(List<InlineResponse20019DataBalances> balances) {
    this.balances = balances;
  }

  public InlineResponse20019Data totalAssetOfBtc(String totalAssetOfBtc) {
    this.totalAssetOfBtc = totalAssetOfBtc;
    return this;
  }

   /**
   * Get totalAssetOfBtc
   * @return totalAssetOfBtc
  **/
  @Schema(example = "0.09905021", description = "")
  public String getTotalAssetOfBtc() {
    return totalAssetOfBtc;
  }

  public void setTotalAssetOfBtc(String totalAssetOfBtc) {
    this.totalAssetOfBtc = totalAssetOfBtc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20019Data inlineResponse20019Data = (InlineResponse20019Data) o;
    return Objects.equals(this.balances, inlineResponse20019Data.balances) &&
        Objects.equals(this.totalAssetOfBtc, inlineResponse20019Data.totalAssetOfBtc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balances, totalAssetOfBtc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20019Data {\n");
    
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("    totalAssetOfBtc: ").append(toIndentedString(totalAssetOfBtc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
