/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20029AssetDetailCTR;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20029AssetDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20029AssetDetail {
  @SerializedName("CTR")
  private InlineResponse20029AssetDetailCTR CTR = null;

  public InlineResponse20029AssetDetail CTR(InlineResponse20029AssetDetailCTR CTR) {
    this.CTR = CTR;
    return this;
  }

   /**
   * Get CTR
   * @return CTR
  **/
  @Schema(description = "")
  public InlineResponse20029AssetDetailCTR getCTR() {
    return CTR;
  }

  public void setCTR(InlineResponse20029AssetDetailCTR CTR) {
    this.CTR = CTR;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20029AssetDetail inlineResponse20029AssetDetail = (InlineResponse20029AssetDetail) o;
    return Objects.equals(this.CTR, inlineResponse20029AssetDetail.CTR);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CTR);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20029AssetDetail {\n");
    
    sb.append("    CTR: ").append(toIndentedString(CTR)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
