/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20021
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20021 {
  @SerializedName("address")
  private String address = null;

  @SerializedName("addressTag")
  private String addressTag = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("coin")
  private String coin = null;

  @SerializedName("insertTime")
  private Integer insertTime = null;

  @SerializedName("network")
  private String network = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("txId")
  private String txId = null;

  public InlineResponse20021 address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(example = "0xddc66e4313fd6c737b6cae67cad90bb4e0ac7092", description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public InlineResponse20021 addressTag(String addressTag) {
    this.addressTag = addressTag;
    return this;
  }

   /**
   * Get addressTag
   * @return addressTag
  **/
  @Schema(description = "")
  public String getAddressTag() {
    return addressTag;
  }

  public void setAddressTag(String addressTag) {
    this.addressTag = addressTag;
  }

  public InlineResponse20021 amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(example = "139.04370000", description = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public InlineResponse20021 coin(String coin) {
    this.coin = coin;
    return this;
  }

   /**
   * Get coin
   * @return coin
  **/
  @Schema(example = "USDT", description = "")
  public String getCoin() {
    return coin;
  }

  public void setCoin(String coin) {
    this.coin = coin;
  }

  public InlineResponse20021 insertTime(Integer insertTime) {
    this.insertTime = insertTime;
    return this;
  }

   /**
   * Get insertTime
   * @return insertTime
  **/
  @Schema(example = "1566791463000", description = "")
  public Integer getInsertTime() {
    return insertTime;
  }

  public void setInsertTime(Integer insertTime) {
    this.insertTime = insertTime;
  }

  public InlineResponse20021 network(String network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @Schema(example = "ETH", description = "")
  public String getNetwork() {
    return network;
  }

  public void setNetwork(String network) {
    this.network = network;
  }

  public InlineResponse20021 status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(example = "1", description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public InlineResponse20021 txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * Get txId
   * @return txId
  **/
  @Schema(example = "0x5759dfe9983a4c7619bce9bc736bb6c26f804091753bf66fa91e7cd5cfeebafd", description = "")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20021 inlineResponse20021 = (InlineResponse20021) o;
    return Objects.equals(this.address, inlineResponse20021.address) &&
        Objects.equals(this.addressTag, inlineResponse20021.addressTag) &&
        Objects.equals(this.amount, inlineResponse20021.amount) &&
        Objects.equals(this.coin, inlineResponse20021.coin) &&
        Objects.equals(this.insertTime, inlineResponse20021.insertTime) &&
        Objects.equals(this.network, inlineResponse20021.network) &&
        Objects.equals(this.status, inlineResponse20021.status) &&
        Objects.equals(this.txId, inlineResponse20021.txId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, addressTag, amount, coin, insertTime, network, status, txId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20021 {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    addressTag: ").append(toIndentedString(addressTag)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    coin: ").append(toIndentedString(coin)).append("\n");
    sb.append("    insertTime: ").append(toIndentedString(insertTime)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
