/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20018NetworkList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20018NetworkList {
  @SerializedName("addressRegex")
  private String addressRegex = null;

  @SerializedName("coin")
  private String coin = null;

  @SerializedName("depositDesc")
  private String depositDesc = null;

  @SerializedName("depositEnable")
  private Boolean depositEnable = null;

  @SerializedName("isDefault")
  private Boolean isDefault = null;

  @SerializedName("memoRegex")
  private String memoRegex = null;

  @SerializedName("minConfirm")
  private Integer minConfirm = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("resetAddressStatus")
  private Boolean resetAddressStatus = null;

  @SerializedName("specialTips")
  private String specialTips = null;

  @SerializedName("unLockConfirm")
  private Integer unLockConfirm = null;

  @SerializedName("withdrawDesc")
  private String withdrawDesc = null;

  @SerializedName("withdrawEnable")
  private Boolean withdrawEnable = null;

  @SerializedName("withdrawFee")
  private String withdrawFee = null;

  @SerializedName("withdrawMin")
  private String withdrawMin = null;

  public InlineResponse20018NetworkList addressRegex(String addressRegex) {
    this.addressRegex = addressRegex;
    return this;
  }

   /**
   * Get addressRegex
   * @return addressRegex
  **/
  @Schema(example = "^(bnb1)[0-9a-z]{38}$", description = "")
  public String getAddressRegex() {
    return addressRegex;
  }

  public void setAddressRegex(String addressRegex) {
    this.addressRegex = addressRegex;
  }

  public InlineResponse20018NetworkList coin(String coin) {
    this.coin = coin;
    return this;
  }

   /**
   * Get coin
   * @return coin
  **/
  @Schema(example = "BTC", description = "")
  public String getCoin() {
    return coin;
  }

  public void setCoin(String coin) {
    this.coin = coin;
  }

  public InlineResponse20018NetworkList depositDesc(String depositDesc) {
    this.depositDesc = depositDesc;
    return this;
  }

   /**
   * Get depositDesc
   * @return depositDesc
  **/
  @Schema(example = "Wallet Maintenance, Deposit Suspended", description = "")
  public String getDepositDesc() {
    return depositDesc;
  }

  public void setDepositDesc(String depositDesc) {
    this.depositDesc = depositDesc;
  }

  public InlineResponse20018NetworkList depositEnable(Boolean depositEnable) {
    this.depositEnable = depositEnable;
    return this;
  }

   /**
   * Get depositEnable
   * @return depositEnable
  **/
  @Schema(example = "false", description = "")
  public Boolean isDepositEnable() {
    return depositEnable;
  }

  public void setDepositEnable(Boolean depositEnable) {
    this.depositEnable = depositEnable;
  }

  public InlineResponse20018NetworkList isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
  @Schema(example = "false", description = "")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public InlineResponse20018NetworkList memoRegex(String memoRegex) {
    this.memoRegex = memoRegex;
    return this;
  }

   /**
   * Get memoRegex
   * @return memoRegex
  **/
  @Schema(example = "^[0-9A-Za-z\\-_]{1,120}$", description = "")
  public String getMemoRegex() {
    return memoRegex;
  }

  public void setMemoRegex(String memoRegex) {
    this.memoRegex = memoRegex;
  }

  public InlineResponse20018NetworkList minConfirm(Integer minConfirm) {
    this.minConfirm = minConfirm;
    return this;
  }

   /**
   * Get minConfirm
   * @return minConfirm
  **/
  @Schema(example = "1", description = "")
  public Integer getMinConfirm() {
    return minConfirm;
  }

  public void setMinConfirm(Integer minConfirm) {
    this.minConfirm = minConfirm;
  }

  public InlineResponse20018NetworkList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "BEP2", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20018NetworkList resetAddressStatus(Boolean resetAddressStatus) {
    this.resetAddressStatus = resetAddressStatus;
    return this;
  }

   /**
   * Get resetAddressStatus
   * @return resetAddressStatus
  **/
  @Schema(example = "false", description = "")
  public Boolean isResetAddressStatus() {
    return resetAddressStatus;
  }

  public void setResetAddressStatus(Boolean resetAddressStatus) {
    this.resetAddressStatus = resetAddressStatus;
  }

  public InlineResponse20018NetworkList specialTips(String specialTips) {
    this.specialTips = specialTips;
    return this;
  }

   /**
   * Get specialTips
   * @return specialTips
  **/
  @Schema(example = "Both a MEMO and an Address are required to successfully deposit your BEP2-BTCB tokens to Binance.", description = "")
  public String getSpecialTips() {
    return specialTips;
  }

  public void setSpecialTips(String specialTips) {
    this.specialTips = specialTips;
  }

  public InlineResponse20018NetworkList unLockConfirm(Integer unLockConfirm) {
    this.unLockConfirm = unLockConfirm;
    return this;
  }

   /**
   * Get unLockConfirm
   * @return unLockConfirm
  **/
  @Schema(example = "0", description = "")
  public Integer getUnLockConfirm() {
    return unLockConfirm;
  }

  public void setUnLockConfirm(Integer unLockConfirm) {
    this.unLockConfirm = unLockConfirm;
  }

  public InlineResponse20018NetworkList withdrawDesc(String withdrawDesc) {
    this.withdrawDesc = withdrawDesc;
    return this;
  }

   /**
   * Get withdrawDesc
   * @return withdrawDesc
  **/
  @Schema(example = "Wallet Maintenance, Withdrawal Suspended", description = "")
  public String getWithdrawDesc() {
    return withdrawDesc;
  }

  public void setWithdrawDesc(String withdrawDesc) {
    this.withdrawDesc = withdrawDesc;
  }

  public InlineResponse20018NetworkList withdrawEnable(Boolean withdrawEnable) {
    this.withdrawEnable = withdrawEnable;
    return this;
  }

   /**
   * Get withdrawEnable
   * @return withdrawEnable
  **/
  @Schema(example = "false", description = "")
  public Boolean isWithdrawEnable() {
    return withdrawEnable;
  }

  public void setWithdrawEnable(Boolean withdrawEnable) {
    this.withdrawEnable = withdrawEnable;
  }

  public InlineResponse20018NetworkList withdrawFee(String withdrawFee) {
    this.withdrawFee = withdrawFee;
    return this;
  }

   /**
   * Get withdrawFee
   * @return withdrawFee
  **/
  @Schema(example = "0.00000220", description = "")
  public String getWithdrawFee() {
    return withdrawFee;
  }

  public void setWithdrawFee(String withdrawFee) {
    this.withdrawFee = withdrawFee;
  }

  public InlineResponse20018NetworkList withdrawMin(String withdrawMin) {
    this.withdrawMin = withdrawMin;
    return this;
  }

   /**
   * Get withdrawMin
   * @return withdrawMin
  **/
  @Schema(example = "0.00000440", description = "")
  public String getWithdrawMin() {
    return withdrawMin;
  }

  public void setWithdrawMin(String withdrawMin) {
    this.withdrawMin = withdrawMin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20018NetworkList inlineResponse20018NetworkList = (InlineResponse20018NetworkList) o;
    return Objects.equals(this.addressRegex, inlineResponse20018NetworkList.addressRegex) &&
        Objects.equals(this.coin, inlineResponse20018NetworkList.coin) &&
        Objects.equals(this.depositDesc, inlineResponse20018NetworkList.depositDesc) &&
        Objects.equals(this.depositEnable, inlineResponse20018NetworkList.depositEnable) &&
        Objects.equals(this.isDefault, inlineResponse20018NetworkList.isDefault) &&
        Objects.equals(this.memoRegex, inlineResponse20018NetworkList.memoRegex) &&
        Objects.equals(this.minConfirm, inlineResponse20018NetworkList.minConfirm) &&
        Objects.equals(this.name, inlineResponse20018NetworkList.name) &&
        Objects.equals(this.resetAddressStatus, inlineResponse20018NetworkList.resetAddressStatus) &&
        Objects.equals(this.specialTips, inlineResponse20018NetworkList.specialTips) &&
        Objects.equals(this.unLockConfirm, inlineResponse20018NetworkList.unLockConfirm) &&
        Objects.equals(this.withdrawDesc, inlineResponse20018NetworkList.withdrawDesc) &&
        Objects.equals(this.withdrawEnable, inlineResponse20018NetworkList.withdrawEnable) &&
        Objects.equals(this.withdrawFee, inlineResponse20018NetworkList.withdrawFee) &&
        Objects.equals(this.withdrawMin, inlineResponse20018NetworkList.withdrawMin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressRegex, coin, depositDesc, depositEnable, isDefault, memoRegex, minConfirm, name, resetAddressStatus, specialTips, unLockConfirm, withdrawDesc, withdrawEnable, withdrawFee, withdrawMin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20018NetworkList {\n");
    
    sb.append("    addressRegex: ").append(toIndentedString(addressRegex)).append("\n");
    sb.append("    coin: ").append(toIndentedString(coin)).append("\n");
    sb.append("    depositDesc: ").append(toIndentedString(depositDesc)).append("\n");
    sb.append("    depositEnable: ").append(toIndentedString(depositEnable)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    memoRegex: ").append(toIndentedString(memoRegex)).append("\n");
    sb.append("    minConfirm: ").append(toIndentedString(minConfirm)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    resetAddressStatus: ").append(toIndentedString(resetAddressStatus)).append("\n");
    sb.append("    specialTips: ").append(toIndentedString(specialTips)).append("\n");
    sb.append("    unLockConfirm: ").append(toIndentedString(unLockConfirm)).append("\n");
    sb.append("    withdrawDesc: ").append(toIndentedString(withdrawDesc)).append("\n");
    sb.append("    withdrawEnable: ").append(toIndentedString(withdrawEnable)).append("\n");
    sb.append("    withdrawFee: ").append(toIndentedString(withdrawFee)).append("\n");
    sb.append("    withdrawMin: ").append(toIndentedString(withdrawMin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
