/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20026ResultsLogs;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20026ResultsRows
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20026ResultsRows {
  @SerializedName("transfered_total")
  private String transferedTotal = null;

  @SerializedName("service_charge_total")
  private String serviceChargeTotal = null;

  @SerializedName("tran_id")
  private Integer tranId = null;

  @SerializedName("logs")
  private List<InlineResponse20026ResultsLogs> logs = null;

  @SerializedName("operate_item")
  private String operateItem = null;

  public InlineResponse20026ResultsRows transferedTotal(String transferedTotal) {
    this.transferedTotal = transferedTotal;
    return this;
  }

   /**
   * Get transferedTotal
   * @return transferedTotal
  **/
  @Schema(example = "0.00132256", description = "")
  public String getTransferedTotal() {
    return transferedTotal;
  }

  public void setTransferedTotal(String transferedTotal) {
    this.transferedTotal = transferedTotal;
  }

  public InlineResponse20026ResultsRows serviceChargeTotal(String serviceChargeTotal) {
    this.serviceChargeTotal = serviceChargeTotal;
    return this;
  }

   /**
   * Get serviceChargeTotal
   * @return serviceChargeTotal
  **/
  @Schema(example = "0.00002699", description = "")
  public String getServiceChargeTotal() {
    return serviceChargeTotal;
  }

  public void setServiceChargeTotal(String serviceChargeTotal) {
    this.serviceChargeTotal = serviceChargeTotal;
  }

  public InlineResponse20026ResultsRows tranId(Integer tranId) {
    this.tranId = tranId;
    return this;
  }

   /**
   * Get tranId
   * @return tranId
  **/
  @Schema(example = "4359321", description = "")
  public Integer getTranId() {
    return tranId;
  }

  public void setTranId(Integer tranId) {
    this.tranId = tranId;
  }

  public InlineResponse20026ResultsRows logs(List<InlineResponse20026ResultsLogs> logs) {
    this.logs = logs;
    return this;
  }

  public InlineResponse20026ResultsRows addLogsItem(InlineResponse20026ResultsLogs logsItem) {
    if (this.logs == null) {
      this.logs = new ArrayList<InlineResponse20026ResultsLogs>();
    }
    this.logs.add(logsItem);
    return this;
  }

   /**
   * Get logs
   * @return logs
  **/
  @Schema(description = "")
  public List<InlineResponse20026ResultsLogs> getLogs() {
    return logs;
  }

  public void setLogs(List<InlineResponse20026ResultsLogs> logs) {
    this.logs = logs;
  }

  public InlineResponse20026ResultsRows operateItem(String operateItem) {
    this.operateItem = operateItem;
    return this;
  }

   /**
   * Get operateItem
   * @return operateItem
  **/
  @Schema(example = "2018-05-03 17:07:04", description = "")
  public String getOperateItem() {
    return operateItem;
  }

  public void setOperateItem(String operateItem) {
    this.operateItem = operateItem;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20026ResultsRows inlineResponse20026ResultsRows = (InlineResponse20026ResultsRows) o;
    return Objects.equals(this.transferedTotal, inlineResponse20026ResultsRows.transferedTotal) &&
        Objects.equals(this.serviceChargeTotal, inlineResponse20026ResultsRows.serviceChargeTotal) &&
        Objects.equals(this.tranId, inlineResponse20026ResultsRows.tranId) &&
        Objects.equals(this.logs, inlineResponse20026ResultsRows.logs) &&
        Objects.equals(this.operateItem, inlineResponse20026ResultsRows.operateItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferedTotal, serviceChargeTotal, tranId, logs, operateItem);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20026ResultsRows {\n");
    
    sb.append("    transferedTotal: ").append(toIndentedString(transferedTotal)).append("\n");
    sb.append("    serviceChargeTotal: ").append(toIndentedString(serviceChargeTotal)).append("\n");
    sb.append("    tranId: ").append(toIndentedString(tranId)).append("\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("    operateItem: ").append(toIndentedString(operateItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
