/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20030TradeFee;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20030
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20030 {
  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("tradeFee")
  private List<InlineResponse20030TradeFee> tradeFee = null;

  public InlineResponse20030 success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @Schema(example = "true", description = "")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public InlineResponse20030 tradeFee(List<InlineResponse20030TradeFee> tradeFee) {
    this.tradeFee = tradeFee;
    return this;
  }

  public InlineResponse20030 addTradeFeeItem(InlineResponse20030TradeFee tradeFeeItem) {
    if (this.tradeFee == null) {
      this.tradeFee = new ArrayList<InlineResponse20030TradeFee>();
    }
    this.tradeFee.add(tradeFeeItem);
    return this;
  }

   /**
   * Get tradeFee
   * @return tradeFee
  **/
  @Schema(description = "")
  public List<InlineResponse20030TradeFee> getTradeFee() {
    return tradeFee;
  }

  public void setTradeFee(List<InlineResponse20030TradeFee> tradeFee) {
    this.tradeFee = tradeFee;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20030 inlineResponse20030 = (InlineResponse20030) o;
    return Objects.equals(this.success, inlineResponse20030.success) &&
        Objects.equals(this.tradeFee, inlineResponse20030.tradeFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, tradeFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20030 {\n");
    
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    tradeFee: ").append(toIndentedString(tradeFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
