/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20011
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20011 {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("base")
  private String base = null;

  @SerializedName("quote")
  private String quote = null;

  @SerializedName("isMarginTrade")
  private Boolean isMarginTrade = null;

  @SerializedName("isBuyAllowed")
  private Boolean isBuyAllowed = null;

  @SerializedName("isSellAllowed")
  private Boolean isSellAllowed = null;

  public InlineResponse20011 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "323355778339572400", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse20011 symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBUSDT", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public InlineResponse20011 base(String base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  @Schema(example = "BTC", description = "")
  public String getBase() {
    return base;
  }

  public void setBase(String base) {
    this.base = base;
  }

  public InlineResponse20011 quote(String quote) {
    this.quote = quote;
    return this;
  }

   /**
   * Get quote
   * @return quote
  **/
  @Schema(example = "USDT", description = "")
  public String getQuote() {
    return quote;
  }

  public void setQuote(String quote) {
    this.quote = quote;
  }

  public InlineResponse20011 isMarginTrade(Boolean isMarginTrade) {
    this.isMarginTrade = isMarginTrade;
    return this;
  }

   /**
   * Get isMarginTrade
   * @return isMarginTrade
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsMarginTrade() {
    return isMarginTrade;
  }

  public void setIsMarginTrade(Boolean isMarginTrade) {
    this.isMarginTrade = isMarginTrade;
  }

  public InlineResponse20011 isBuyAllowed(Boolean isBuyAllowed) {
    this.isBuyAllowed = isBuyAllowed;
    return this;
  }

   /**
   * Get isBuyAllowed
   * @return isBuyAllowed
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsBuyAllowed() {
    return isBuyAllowed;
  }

  public void setIsBuyAllowed(Boolean isBuyAllowed) {
    this.isBuyAllowed = isBuyAllowed;
  }

  public InlineResponse20011 isSellAllowed(Boolean isSellAllowed) {
    this.isSellAllowed = isSellAllowed;
    return this;
  }

   /**
   * Get isSellAllowed
   * @return isSellAllowed
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsSellAllowed() {
    return isSellAllowed;
  }

  public void setIsSellAllowed(Boolean isSellAllowed) {
    this.isSellAllowed = isSellAllowed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011 inlineResponse20011 = (InlineResponse20011) o;
    return Objects.equals(this.id, inlineResponse20011.id) &&
        Objects.equals(this.symbol, inlineResponse20011.symbol) &&
        Objects.equals(this.base, inlineResponse20011.base) &&
        Objects.equals(this.quote, inlineResponse20011.quote) &&
        Objects.equals(this.isMarginTrade, inlineResponse20011.isMarginTrade) &&
        Objects.equals(this.isBuyAllowed, inlineResponse20011.isBuyAllowed) &&
        Objects.equals(this.isSellAllowed, inlineResponse20011.isSellAllowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, symbol, base, quote, isMarginTrade, isBuyAllowed, isSellAllowed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    quote: ").append(toIndentedString(quote)).append("\n");
    sb.append("    isMarginTrade: ").append(toIndentedString(isMarginTrade)).append("\n");
    sb.append("    isBuyAllowed: ").append(toIndentedString(isBuyAllowed)).append("\n");
    sb.append("    isSellAllowed: ").append(toIndentedString(isSellAllowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
