/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20016Rows
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20016Rows {
  @SerializedName("asset")
  private String asset = null;

  @SerializedName("interest")
  private String interest = null;

  @SerializedName("interestAccuredTime")
  private Integer interestAccuredTime = null;

  @SerializedName("interestRate")
  private String interestRate = null;

  @SerializedName("principal")
  private String principal = null;

  @SerializedName("type")
  private String type = null;

  public InlineResponse20016Rows asset(String asset) {
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @Schema(example = "BNB", description = "")
  public String getAsset() {
    return asset;
  }

  public void setAsset(String asset) {
    this.asset = asset;
  }

  public InlineResponse20016Rows interest(String interest) {
    this.interest = interest;
    return this;
  }

   /**
   * Get interest
   * @return interest
  **/
  @Schema(example = "0.01866667", description = "")
  public String getInterest() {
    return interest;
  }

  public void setInterest(String interest) {
    this.interest = interest;
  }

  public InlineResponse20016Rows interestAccuredTime(Integer interestAccuredTime) {
    this.interestAccuredTime = interestAccuredTime;
    return this;
  }

   /**
   * Get interestAccuredTime
   * @return interestAccuredTime
  **/
  @Schema(example = "1566813600", description = "")
  public Integer getInterestAccuredTime() {
    return interestAccuredTime;
  }

  public void setInterestAccuredTime(Integer interestAccuredTime) {
    this.interestAccuredTime = interestAccuredTime;
  }

  public InlineResponse20016Rows interestRate(String interestRate) {
    this.interestRate = interestRate;
    return this;
  }

   /**
   * Get interestRate
   * @return interestRate
  **/
  @Schema(example = "0.01600000", description = "")
  public String getInterestRate() {
    return interestRate;
  }

  public void setInterestRate(String interestRate) {
    this.interestRate = interestRate;
  }

  public InlineResponse20016Rows principal(String principal) {
    this.principal = principal;
    return this;
  }

   /**
   * Get principal
   * @return principal
  **/
  @Schema(example = "36.22000000", description = "")
  public String getPrincipal() {
    return principal;
  }

  public void setPrincipal(String principal) {
    this.principal = principal;
  }

  public InlineResponse20016Rows type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(example = "ON_BORROW", description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20016Rows inlineResponse20016Rows = (InlineResponse20016Rows) o;
    return Objects.equals(this.asset, inlineResponse20016Rows.asset) &&
        Objects.equals(this.interest, inlineResponse20016Rows.interest) &&
        Objects.equals(this.interestAccuredTime, inlineResponse20016Rows.interestAccuredTime) &&
        Objects.equals(this.interestRate, inlineResponse20016Rows.interestRate) &&
        Objects.equals(this.principal, inlineResponse20016Rows.principal) &&
        Objects.equals(this.type, inlineResponse20016Rows.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asset, interest, interestAccuredTime, interestRate, principal, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20016Rows {\n");
    
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    interest: ").append(toIndentedString(interest)).append("\n");
    sb.append("    interestAccuredTime: ").append(toIndentedString(interestAccuredTime)).append("\n");
    sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
    sb.append("    principal: ").append(toIndentedString(principal)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
