/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20027TransferResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class InlineResponse20027TransferResult {
  @SerializedName("amount")
  private String amount = null;

  @SerializedName("fromAsset")
  private String fromAsset = null;

  @SerializedName("operateTime")
  private Integer operateTime = null;

  @SerializedName("serviceChargeAmount")
  private String serviceChargeAmount = null;

  @SerializedName("tranId")
  private Integer tranId = null;

  @SerializedName("transferedAmount")
  private String transferedAmount = null;

  public InlineResponse20027TransferResult amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(example = "0.03000000", description = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public InlineResponse20027TransferResult fromAsset(String fromAsset) {
    this.fromAsset = fromAsset;
    return this;
  }

   /**
   * Get fromAsset
   * @return fromAsset
  **/
  @Schema(example = "ETH", description = "")
  public String getFromAsset() {
    return fromAsset;
  }

  public void setFromAsset(String fromAsset) {
    this.fromAsset = fromAsset;
  }

  public InlineResponse20027TransferResult operateTime(Integer operateTime) {
    this.operateTime = operateTime;
    return this;
  }

   /**
   * Get operateTime
   * @return operateTime
  **/
  @Schema(example = "1563368549307", description = "")
  public Integer getOperateTime() {
    return operateTime;
  }

  public void setOperateTime(Integer operateTime) {
    this.operateTime = operateTime;
  }

  public InlineResponse20027TransferResult serviceChargeAmount(String serviceChargeAmount) {
    this.serviceChargeAmount = serviceChargeAmount;
    return this;
  }

   /**
   * Get serviceChargeAmount
   * @return serviceChargeAmount
  **/
  @Schema(example = "0.00500000", description = "")
  public String getServiceChargeAmount() {
    return serviceChargeAmount;
  }

  public void setServiceChargeAmount(String serviceChargeAmount) {
    this.serviceChargeAmount = serviceChargeAmount;
  }

  public InlineResponse20027TransferResult tranId(Integer tranId) {
    this.tranId = tranId;
    return this;
  }

   /**
   * Get tranId
   * @return tranId
  **/
  @Schema(example = "2970932918", description = "")
  public Integer getTranId() {
    return tranId;
  }

  public void setTranId(Integer tranId) {
    this.tranId = tranId;
  }

  public InlineResponse20027TransferResult transferedAmount(String transferedAmount) {
    this.transferedAmount = transferedAmount;
    return this;
  }

   /**
   * Get transferedAmount
   * @return transferedAmount
  **/
  @Schema(example = "0.25000000", description = "")
  public String getTransferedAmount() {
    return transferedAmount;
  }

  public void setTransferedAmount(String transferedAmount) {
    this.transferedAmount = transferedAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20027TransferResult inlineResponse20027TransferResult = (InlineResponse20027TransferResult) o;
    return Objects.equals(this.amount, inlineResponse20027TransferResult.amount) &&
        Objects.equals(this.fromAsset, inlineResponse20027TransferResult.fromAsset) &&
        Objects.equals(this.operateTime, inlineResponse20027TransferResult.operateTime) &&
        Objects.equals(this.serviceChargeAmount, inlineResponse20027TransferResult.serviceChargeAmount) &&
        Objects.equals(this.tranId, inlineResponse20027TransferResult.tranId) &&
        Objects.equals(this.transferedAmount, inlineResponse20027TransferResult.transferedAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, fromAsset, operateTime, serviceChargeAmount, tranId, transferedAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20027TransferResult {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    fromAsset: ").append(toIndentedString(fromAsset)).append("\n");
    sb.append("    operateTime: ").append(toIndentedString(operateTime)).append("\n");
    sb.append("    serviceChargeAmount: ").append(toIndentedString(serviceChargeAmount)).append("\n");
    sb.append("    tranId: ").append(toIndentedString(tranId)).append("\n");
    sb.append("    transferedAmount: ").append(toIndentedString(transferedAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
