/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MarginTrade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class MarginTrade {
  @SerializedName("commission")
  private String commission = null;

  @SerializedName("commissionAsset")
  private String commissionAsset = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("isBestMatch")
  private Boolean isBestMatch = null;

  @SerializedName("isBuyer")
  private Boolean isBuyer = null;

  @SerializedName("isMaker")
  private Boolean isMaker = null;

  @SerializedName("orderId")
  private Integer orderId = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("qty")
  private String qty = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("time")
  private Integer time = null;

  public MarginTrade commission(String commission) {
    this.commission = commission;
    return this;
  }

   /**
   * Get commission
   * @return commission
  **/
  @Schema(example = "0.00006000", description = "")
  public String getCommission() {
    return commission;
  }

  public void setCommission(String commission) {
    this.commission = commission;
  }

  public MarginTrade commissionAsset(String commissionAsset) {
    this.commissionAsset = commissionAsset;
    return this;
  }

   /**
   * Get commissionAsset
   * @return commissionAsset
  **/
  @Schema(example = "BTC", description = "")
  public String getCommissionAsset() {
    return commissionAsset;
  }

  public void setCommissionAsset(String commissionAsset) {
    this.commissionAsset = commissionAsset;
  }

  public MarginTrade id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "28", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MarginTrade isBestMatch(Boolean isBestMatch) {
    this.isBestMatch = isBestMatch;
    return this;
  }

   /**
   * Get isBestMatch
   * @return isBestMatch
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsBestMatch() {
    return isBestMatch;
  }

  public void setIsBestMatch(Boolean isBestMatch) {
    this.isBestMatch = isBestMatch;
  }

  public MarginTrade isBuyer(Boolean isBuyer) {
    this.isBuyer = isBuyer;
    return this;
  }

   /**
   * Get isBuyer
   * @return isBuyer
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsBuyer() {
    return isBuyer;
  }

  public void setIsBuyer(Boolean isBuyer) {
    this.isBuyer = isBuyer;
  }

  public MarginTrade isMaker(Boolean isMaker) {
    this.isMaker = isMaker;
    return this;
  }

   /**
   * Get isMaker
   * @return isMaker
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsMaker() {
    return isMaker;
  }

  public void setIsMaker(Boolean isMaker) {
    this.isMaker = isMaker;
  }

  public MarginTrade orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(example = "28", description = "")
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public MarginTrade price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(example = "0.02000000", description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public MarginTrade qty(String qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @Schema(example = "1.02000000", description = "")
  public String getQty() {
    return qty;
  }

  public void setQty(String qty) {
    this.qty = qty;
  }

  public MarginTrade symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBBTC", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public MarginTrade time(Integer time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @Schema(example = "1507725176595", description = "")
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarginTrade marginTrade = (MarginTrade) o;
    return Objects.equals(this.commission, marginTrade.commission) &&
        Objects.equals(this.commissionAsset, marginTrade.commissionAsset) &&
        Objects.equals(this.id, marginTrade.id) &&
        Objects.equals(this.isBestMatch, marginTrade.isBestMatch) &&
        Objects.equals(this.isBuyer, marginTrade.isBuyer) &&
        Objects.equals(this.isMaker, marginTrade.isMaker) &&
        Objects.equals(this.orderId, marginTrade.orderId) &&
        Objects.equals(this.price, marginTrade.price) &&
        Objects.equals(this.qty, marginTrade.qty) &&
        Objects.equals(this.symbol, marginTrade.symbol) &&
        Objects.equals(this.time, marginTrade.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commission, commissionAsset, id, isBestMatch, isBuyer, isMaker, orderId, price, qty, symbol, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarginTrade {\n");
    
    sb.append("    commission: ").append(toIndentedString(commission)).append("\n");
    sb.append("    commissionAsset: ").append(toIndentedString(commissionAsset)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isBestMatch: ").append(toIndentedString(isBestMatch)).append("\n");
    sb.append("    isBuyer: ").append(toIndentedString(isBuyer)).append("\n");
    sb.append("    isMaker: ").append(toIndentedString(isMaker)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
