/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MarginOrder
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class MarginOrder {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("orderId")
  private Integer orderId = null;

  @SerializedName("origClientOrderId")
  private String origClientOrderId = null;

  @SerializedName("clientOrderId")
  private String clientOrderId = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("origQty")
  private String origQty = null;

  @SerializedName("executedQty")
  private String executedQty = null;

  @SerializedName("cummulativeQuoteQty")
  private String cummulativeQuoteQty = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("timeInForce")
  private String timeInForce = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("side")
  private String side = null;

  public MarginOrder symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBBTC", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public MarginOrder orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(example = "28", description = "")
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public MarginOrder origClientOrderId(String origClientOrderId) {
    this.origClientOrderId = origClientOrderId;
    return this;
  }

   /**
   * Get origClientOrderId
   * @return origClientOrderId
  **/
  @Schema(example = "msXkySR3u5uYwpvRMFsi3u", description = "")
  public String getOrigClientOrderId() {
    return origClientOrderId;
  }

  public void setOrigClientOrderId(String origClientOrderId) {
    this.origClientOrderId = origClientOrderId;
  }

  public MarginOrder clientOrderId(String clientOrderId) {
    this.clientOrderId = clientOrderId;
    return this;
  }

   /**
   * Get clientOrderId
   * @return clientOrderId
  **/
  @Schema(example = "6gCrw2kRUAF9CvJDGP16IP", description = "")
  public String getClientOrderId() {
    return clientOrderId;
  }

  public void setClientOrderId(String clientOrderId) {
    this.clientOrderId = clientOrderId;
  }

  public MarginOrder price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(example = "1.00000000", description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public MarginOrder origQty(String origQty) {
    this.origQty = origQty;
    return this;
  }

   /**
   * Get origQty
   * @return origQty
  **/
  @Schema(example = "10.00000000", description = "")
  public String getOrigQty() {
    return origQty;
  }

  public void setOrigQty(String origQty) {
    this.origQty = origQty;
  }

  public MarginOrder executedQty(String executedQty) {
    this.executedQty = executedQty;
    return this;
  }

   /**
   * Get executedQty
   * @return executedQty
  **/
  @Schema(example = "10.00000000", description = "")
  public String getExecutedQty() {
    return executedQty;
  }

  public void setExecutedQty(String executedQty) {
    this.executedQty = executedQty;
  }

  public MarginOrder cummulativeQuoteQty(String cummulativeQuoteQty) {
    this.cummulativeQuoteQty = cummulativeQuoteQty;
    return this;
  }

   /**
   * Get cummulativeQuoteQty
   * @return cummulativeQuoteQty
  **/
  @Schema(example = "10.00000000", description = "")
  public String getCummulativeQuoteQty() {
    return cummulativeQuoteQty;
  }

  public void setCummulativeQuoteQty(String cummulativeQuoteQty) {
    this.cummulativeQuoteQty = cummulativeQuoteQty;
  }

  public MarginOrder status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(example = "CANCELED", description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public MarginOrder timeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * Get timeInForce
   * @return timeInForce
  **/
  @Schema(example = "GTC", description = "")
  public String getTimeInForce() {
    return timeInForce;
  }

  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }

  public MarginOrder type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(example = "LIMIT", description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public MarginOrder side(String side) {
    this.side = side;
    return this;
  }

   /**
   * Get side
   * @return side
  **/
  @Schema(example = "SELL", description = "")
  public String getSide() {
    return side;
  }

  public void setSide(String side) {
    this.side = side;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarginOrder marginOrder = (MarginOrder) o;
    return Objects.equals(this.symbol, marginOrder.symbol) &&
        Objects.equals(this.orderId, marginOrder.orderId) &&
        Objects.equals(this.origClientOrderId, marginOrder.origClientOrderId) &&
        Objects.equals(this.clientOrderId, marginOrder.clientOrderId) &&
        Objects.equals(this.price, marginOrder.price) &&
        Objects.equals(this.origQty, marginOrder.origQty) &&
        Objects.equals(this.executedQty, marginOrder.executedQty) &&
        Objects.equals(this.cummulativeQuoteQty, marginOrder.cummulativeQuoteQty) &&
        Objects.equals(this.status, marginOrder.status) &&
        Objects.equals(this.timeInForce, marginOrder.timeInForce) &&
        Objects.equals(this.type, marginOrder.type) &&
        Objects.equals(this.side, marginOrder.side);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, orderId, origClientOrderId, clientOrderId, price, origQty, executedQty, cummulativeQuoteQty, status, timeInForce, type, side);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarginOrder {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    origClientOrderId: ").append(toIndentedString(origClientOrderId)).append("\n");
    sb.append("    clientOrderId: ").append(toIndentedString(clientOrderId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    origQty: ").append(toIndentedString(origQty)).append("\n");
    sb.append("    executedQty: ").append(toIndentedString(executedQty)).append("\n");
    sb.append("    cummulativeQuoteQty: ").append(toIndentedString(cummulativeQuoteQty)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
