/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MarginOrderDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class MarginOrderDetail {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("orderId")
  private Integer orderId = null;

  @SerializedName("clientOrderId")
  private String clientOrderId = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("origQty")
  private String origQty = null;

  @SerializedName("executedQty")
  private String executedQty = null;

  @SerializedName("cummulativeQuoteQty")
  private String cummulativeQuoteQty = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("stopPrice")
  private String stopPrice = null;

  @SerializedName("time")
  private Integer time = null;

  @SerializedName("timeInForce")
  private String timeInForce = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("side")
  private String side = null;

  @SerializedName("icebergQty")
  private String icebergQty = null;

  @SerializedName("isWorking")
  private Boolean isWorking = null;

  @SerializedName("updateTime")
  private Integer updateTime = null;

  public MarginOrderDetail symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBBTC", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public MarginOrderDetail orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(example = "28", description = "")
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public MarginOrderDetail clientOrderId(String clientOrderId) {
    this.clientOrderId = clientOrderId;
    return this;
  }

   /**
   * Get clientOrderId
   * @return clientOrderId
  **/
  @Schema(example = "6gCrw2kRUAF9CvJDGP16IP", description = "")
  public String getClientOrderId() {
    return clientOrderId;
  }

  public void setClientOrderId(String clientOrderId) {
    this.clientOrderId = clientOrderId;
  }

  public MarginOrderDetail price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(example = "1.00000000", description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public MarginOrderDetail origQty(String origQty) {
    this.origQty = origQty;
    return this;
  }

   /**
   * Get origQty
   * @return origQty
  **/
  @Schema(example = "10.00000000", description = "")
  public String getOrigQty() {
    return origQty;
  }

  public void setOrigQty(String origQty) {
    this.origQty = origQty;
  }

  public MarginOrderDetail executedQty(String executedQty) {
    this.executedQty = executedQty;
    return this;
  }

   /**
   * Get executedQty
   * @return executedQty
  **/
  @Schema(example = "10.00000000", description = "")
  public String getExecutedQty() {
    return executedQty;
  }

  public void setExecutedQty(String executedQty) {
    this.executedQty = executedQty;
  }

  public MarginOrderDetail cummulativeQuoteQty(String cummulativeQuoteQty) {
    this.cummulativeQuoteQty = cummulativeQuoteQty;
    return this;
  }

   /**
   * Get cummulativeQuoteQty
   * @return cummulativeQuoteQty
  **/
  @Schema(example = "10.00000000", description = "")
  public String getCummulativeQuoteQty() {
    return cummulativeQuoteQty;
  }

  public void setCummulativeQuoteQty(String cummulativeQuoteQty) {
    this.cummulativeQuoteQty = cummulativeQuoteQty;
  }

  public MarginOrderDetail status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(example = "CANCELED", description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public MarginOrderDetail stopPrice(String stopPrice) {
    this.stopPrice = stopPrice;
    return this;
  }

   /**
   * Get stopPrice
   * @return stopPrice
  **/
  @Schema(example = "1.00000000", description = "")
  public String getStopPrice() {
    return stopPrice;
  }

  public void setStopPrice(String stopPrice) {
    this.stopPrice = stopPrice;
  }

  public MarginOrderDetail time(Integer time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @Schema(example = "1562133008725", description = "")
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }

  public MarginOrderDetail timeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * Get timeInForce
   * @return timeInForce
  **/
  @Schema(example = "GTC", description = "")
  public String getTimeInForce() {
    return timeInForce;
  }

  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }

  public MarginOrderDetail type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(example = "LIMIT", description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public MarginOrderDetail side(String side) {
    this.side = side;
    return this;
  }

   /**
   * Get side
   * @return side
  **/
  @Schema(example = "SELL", description = "")
  public String getSide() {
    return side;
  }

  public void setSide(String side) {
    this.side = side;
  }

  public MarginOrderDetail icebergQty(String icebergQty) {
    this.icebergQty = icebergQty;
    return this;
  }

   /**
   * Get icebergQty
   * @return icebergQty
  **/
  @Schema(example = "0.00000000", description = "")
  public String getIcebergQty() {
    return icebergQty;
  }

  public void setIcebergQty(String icebergQty) {
    this.icebergQty = icebergQty;
  }

  public MarginOrderDetail isWorking(Boolean isWorking) {
    this.isWorking = isWorking;
    return this;
  }

   /**
   * Get isWorking
   * @return isWorking
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsWorking() {
    return isWorking;
  }

  public void setIsWorking(Boolean isWorking) {
    this.isWorking = isWorking;
  }

  public MarginOrderDetail updateTime(Integer updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @Schema(example = "1562133008725", description = "")
  public Integer getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(Integer updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarginOrderDetail marginOrderDetail = (MarginOrderDetail) o;
    return Objects.equals(this.symbol, marginOrderDetail.symbol) &&
        Objects.equals(this.orderId, marginOrderDetail.orderId) &&
        Objects.equals(this.clientOrderId, marginOrderDetail.clientOrderId) &&
        Objects.equals(this.price, marginOrderDetail.price) &&
        Objects.equals(this.origQty, marginOrderDetail.origQty) &&
        Objects.equals(this.executedQty, marginOrderDetail.executedQty) &&
        Objects.equals(this.cummulativeQuoteQty, marginOrderDetail.cummulativeQuoteQty) &&
        Objects.equals(this.status, marginOrderDetail.status) &&
        Objects.equals(this.stopPrice, marginOrderDetail.stopPrice) &&
        Objects.equals(this.time, marginOrderDetail.time) &&
        Objects.equals(this.timeInForce, marginOrderDetail.timeInForce) &&
        Objects.equals(this.type, marginOrderDetail.type) &&
        Objects.equals(this.side, marginOrderDetail.side) &&
        Objects.equals(this.icebergQty, marginOrderDetail.icebergQty) &&
        Objects.equals(this.isWorking, marginOrderDetail.isWorking) &&
        Objects.equals(this.updateTime, marginOrderDetail.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, orderId, clientOrderId, price, origQty, executedQty, cummulativeQuoteQty, status, stopPrice, time, timeInForce, type, side, icebergQty, isWorking, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarginOrderDetail {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    clientOrderId: ").append(toIndentedString(clientOrderId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    origQty: ").append(toIndentedString(origQty)).append("\n");
    sb.append("    executedQty: ").append(toIndentedString(executedQty)).append("\n");
    sb.append("    cummulativeQuoteQty: ").append(toIndentedString(cummulativeQuoteQty)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    stopPrice: ").append(toIndentedString(stopPrice)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    icebergQty: ").append(toIndentedString(icebergQty)).append("\n");
    sb.append("    isWorking: ").append(toIndentedString(isWorking)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
