/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MyTrade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class MyTrade {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("orderId")
  private Integer orderId = null;

  @SerializedName("orderListId")
  private Integer orderListId = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("qty")
  private String qty = null;

  @SerializedName("quoteQty")
  private String quoteQty = null;

  @SerializedName("commission")
  private String commission = null;

  @SerializedName("commissionAsset")
  private String commissionAsset = null;

  @SerializedName("time")
  private Integer time = null;

  @SerializedName("isBuyer")
  private Boolean isBuyer = null;

  @SerializedName("isMaker")
  private Boolean isMaker = null;

  @SerializedName("isBestMatch")
  private Boolean isBestMatch = null;

  public MyTrade symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBUSDT", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public MyTrade id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * trade id
   * @return id
  **/
  @Schema(example = "345196462", description = "trade id")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MyTrade orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(example = "345196462", description = "")
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public MyTrade orderListId(Integer orderListId) {
    this.orderListId = orderListId;
    return this;
  }

   /**
   * Get orderListId
   * @return orderListId
  **/
  @Schema(example = "345196462", description = "")
  public Integer getOrderListId() {
    return orderListId;
  }

  public void setOrderListId(Integer orderListId) {
    this.orderListId = orderListId;
  }

  public MyTrade price(String price) {
    this.price = price;
    return this;
  }

   /**
   * price
   * @return price
  **/
  @Schema(example = "9638.99000000", description = "price")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public MyTrade qty(String qty) {
    this.qty = qty;
    return this;
  }

   /**
   * amount of base asset
   * @return qty
  **/
  @Schema(example = "0.02077200", description = "amount of base asset")
  public String getQty() {
    return qty;
  }

  public void setQty(String qty) {
    this.qty = qty;
  }

  public MyTrade quoteQty(String quoteQty) {
    this.quoteQty = quoteQty;
    return this;
  }

   /**
   * amount of quote asset
   * @return quoteQty
  **/
  @Schema(example = "0.02077200", description = "amount of quote asset")
  public String getQuoteQty() {
    return quoteQty;
  }

  public void setQuoteQty(String quoteQty) {
    this.quoteQty = quoteQty;
  }

  public MyTrade commission(String commission) {
    this.commission = commission;
    return this;
  }

   /**
   * Get commission
   * @return commission
  **/
  @Schema(example = "0.02077200", description = "")
  public String getCommission() {
    return commission;
  }

  public void setCommission(String commission) {
    this.commission = commission;
  }

  public MyTrade commissionAsset(String commissionAsset) {
    this.commissionAsset = commissionAsset;
    return this;
  }

   /**
   * Get commissionAsset
   * @return commissionAsset
  **/
  @Schema(example = "BNB", description = "")
  public String getCommissionAsset() {
    return commissionAsset;
  }

  public void setCommissionAsset(String commissionAsset) {
    this.commissionAsset = commissionAsset;
  }

  public MyTrade time(Integer time) {
    this.time = time;
    return this;
  }

   /**
   * trade timestamp
   * @return time
  **/
  @Schema(example = "1592887772684", description = "trade timestamp")
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }

  public MyTrade isBuyer(Boolean isBuyer) {
    this.isBuyer = isBuyer;
    return this;
  }

   /**
   * Get isBuyer
   * @return isBuyer
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsBuyer() {
    return isBuyer;
  }

  public void setIsBuyer(Boolean isBuyer) {
    this.isBuyer = isBuyer;
  }

  public MyTrade isMaker(Boolean isMaker) {
    this.isMaker = isMaker;
    return this;
  }

   /**
   * Get isMaker
   * @return isMaker
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsMaker() {
    return isMaker;
  }

  public void setIsMaker(Boolean isMaker) {
    this.isMaker = isMaker;
  }

  public MyTrade isBestMatch(Boolean isBestMatch) {
    this.isBestMatch = isBestMatch;
    return this;
  }

   /**
   * Get isBestMatch
   * @return isBestMatch
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsBestMatch() {
    return isBestMatch;
  }

  public void setIsBestMatch(Boolean isBestMatch) {
    this.isBestMatch = isBestMatch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyTrade myTrade = (MyTrade) o;
    return Objects.equals(this.symbol, myTrade.symbol) &&
        Objects.equals(this.id, myTrade.id) &&
        Objects.equals(this.orderId, myTrade.orderId) &&
        Objects.equals(this.orderListId, myTrade.orderListId) &&
        Objects.equals(this.price, myTrade.price) &&
        Objects.equals(this.qty, myTrade.qty) &&
        Objects.equals(this.quoteQty, myTrade.quoteQty) &&
        Objects.equals(this.commission, myTrade.commission) &&
        Objects.equals(this.commissionAsset, myTrade.commissionAsset) &&
        Objects.equals(this.time, myTrade.time) &&
        Objects.equals(this.isBuyer, myTrade.isBuyer) &&
        Objects.equals(this.isMaker, myTrade.isMaker) &&
        Objects.equals(this.isBestMatch, myTrade.isBestMatch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, id, orderId, orderListId, price, qty, quoteQty, commission, commissionAsset, time, isBuyer, isMaker, isBestMatch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyTrade {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderListId: ").append(toIndentedString(orderListId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    quoteQty: ").append(toIndentedString(quoteQty)).append("\n");
    sb.append("    commission: ").append(toIndentedString(commission)).append("\n");
    sb.append("    commissionAsset: ").append(toIndentedString(commissionAsset)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    isBuyer: ").append(toIndentedString(isBuyer)).append("\n");
    sb.append("    isMaker: ").append(toIndentedString(isMaker)).append("\n");
    sb.append("    isBestMatch: ").append(toIndentedString(isBestMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
