/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OCOOrderOrders;
import io.swagger.client.model.Order;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * OCOOrderReport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class OCOOrderReport {
  @SerializedName("orderListId")
  private Integer orderListId = null;

  @SerializedName("contingencyType")
  private String contingencyType = null;

  @SerializedName("listStatusType")
  private String listStatusType = null;

  @SerializedName("listOrderStatus")
  private String listOrderStatus = null;

  @SerializedName("listClientOrderId")
  private String listClientOrderId = null;

  @SerializedName("transactionTime")
  private Integer transactionTime = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("orders")
  private List<OCOOrderOrders> orders = null;

  @SerializedName("orderReports")
  private List<Order> orderReports = null;

  public OCOOrderReport orderListId(Integer orderListId) {
    this.orderListId = orderListId;
    return this;
  }

   /**
   * Get orderListId
   * @return orderListId
  **/
  @Schema(example = "3159531", description = "")
  public Integer getOrderListId() {
    return orderListId;
  }

  public void setOrderListId(Integer orderListId) {
    this.orderListId = orderListId;
  }

  public OCOOrderReport contingencyType(String contingencyType) {
    this.contingencyType = contingencyType;
    return this;
  }

   /**
   * Get contingencyType
   * @return contingencyType
  **/
  @Schema(example = "OCO", description = "")
  public String getContingencyType() {
    return contingencyType;
  }

  public void setContingencyType(String contingencyType) {
    this.contingencyType = contingencyType;
  }

  public OCOOrderReport listStatusType(String listStatusType) {
    this.listStatusType = listStatusType;
    return this;
  }

   /**
   * Get listStatusType
   * @return listStatusType
  **/
  @Schema(example = "ALL_DONE", description = "")
  public String getListStatusType() {
    return listStatusType;
  }

  public void setListStatusType(String listStatusType) {
    this.listStatusType = listStatusType;
  }

  public OCOOrderReport listOrderStatus(String listOrderStatus) {
    this.listOrderStatus = listOrderStatus;
    return this;
  }

   /**
   * Get listOrderStatus
   * @return listOrderStatus
  **/
  @Schema(example = "ALL_DONE", description = "")
  public String getListOrderStatus() {
    return listOrderStatus;
  }

  public void setListOrderStatus(String listOrderStatus) {
    this.listOrderStatus = listOrderStatus;
  }

  public OCOOrderReport listClientOrderId(String listClientOrderId) {
    this.listClientOrderId = listClientOrderId;
    return this;
  }

   /**
   * Get listClientOrderId
   * @return listClientOrderId
  **/
  @Schema(example = "jhaxNE9gi6rItxyh8pZsoM", description = "")
  public String getListClientOrderId() {
    return listClientOrderId;
  }

  public void setListClientOrderId(String listClientOrderId) {
    this.listClientOrderId = listClientOrderId;
  }

  public OCOOrderReport transactionTime(Integer transactionTime) {
    this.transactionTime = transactionTime;
    return this;
  }

   /**
   * Get transactionTime
   * @return transactionTime
  **/
  @Schema(example = "1585261352335", description = "")
  public Integer getTransactionTime() {
    return transactionTime;
  }

  public void setTransactionTime(Integer transactionTime) {
    this.transactionTime = transactionTime;
  }

  public OCOOrderReport symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBUSDT", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public OCOOrderReport orders(List<OCOOrderOrders> orders) {
    this.orders = orders;
    return this;
  }

  public OCOOrderReport addOrdersItem(OCOOrderOrders ordersItem) {
    if (this.orders == null) {
      this.orders = new ArrayList<OCOOrderOrders>();
    }
    this.orders.add(ordersItem);
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  @Schema(description = "")
  public List<OCOOrderOrders> getOrders() {
    return orders;
  }

  public void setOrders(List<OCOOrderOrders> orders) {
    this.orders = orders;
  }

  public OCOOrderReport orderReports(List<Order> orderReports) {
    this.orderReports = orderReports;
    return this;
  }

  public OCOOrderReport addOrderReportsItem(Order orderReportsItem) {
    if (this.orderReports == null) {
      this.orderReports = new ArrayList<Order>();
    }
    this.orderReports.add(orderReportsItem);
    return this;
  }

   /**
   * Get orderReports
   * @return orderReports
  **/
  @Schema(description = "")
  public List<Order> getOrderReports() {
    return orderReports;
  }

  public void setOrderReports(List<Order> orderReports) {
    this.orderReports = orderReports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OCOOrderReport ocOOrderReport = (OCOOrderReport) o;
    return Objects.equals(this.orderListId, ocOOrderReport.orderListId) &&
        Objects.equals(this.contingencyType, ocOOrderReport.contingencyType) &&
        Objects.equals(this.listStatusType, ocOOrderReport.listStatusType) &&
        Objects.equals(this.listOrderStatus, ocOOrderReport.listOrderStatus) &&
        Objects.equals(this.listClientOrderId, ocOOrderReport.listClientOrderId) &&
        Objects.equals(this.transactionTime, ocOOrderReport.transactionTime) &&
        Objects.equals(this.symbol, ocOOrderReport.symbol) &&
        Objects.equals(this.orders, ocOOrderReport.orders) &&
        Objects.equals(this.orderReports, ocOOrderReport.orderReports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderListId, contingencyType, listStatusType, listOrderStatus, listClientOrderId, transactionTime, symbol, orders, orderReports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OCOOrderReport {\n");
    
    sb.append("    orderListId: ").append(toIndentedString(orderListId)).append("\n");
    sb.append("    contingencyType: ").append(toIndentedString(contingencyType)).append("\n");
    sb.append("    listStatusType: ").append(toIndentedString(listStatusType)).append("\n");
    sb.append("    listOrderStatus: ").append(toIndentedString(listOrderStatus)).append("\n");
    sb.append("    listClientOrderId: ").append(toIndentedString(listClientOrderId)).append("\n");
    sb.append("    transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    orderReports: ").append(toIndentedString(orderReports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
