/*
 * Binance SPOT Public API
 * The swagger file of Binance Public API  API documents:   - [https://github.com/binance-exchange/binance-official-api-docs](https://github.com/binance-exchange/binance-official-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Ticker
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-26T21:41:41.962Z[GMT]")
public class Ticker implements OneOfinlineResponse2004 {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("priceChange")
  private String priceChange = null;

  @SerializedName("priceChangePercent")
  private String priceChangePercent = null;

  @SerializedName("prevClosePrice")
  private String prevClosePrice = null;

  @SerializedName("lastPrice")
  private String lastPrice = null;

  @SerializedName("bidPrice")
  private String bidPrice = null;

  @SerializedName("bidQty")
  private String bidQty = null;

  @SerializedName("askPrice")
  private String askPrice = null;

  @SerializedName("askQty")
  private String askQty = null;

  @SerializedName("openPrice")
  private String openPrice = null;

  @SerializedName("highPrice")
  private String highPrice = null;

  @SerializedName("lowPrice")
  private String lowPrice = null;

  @SerializedName("volume")
  private String volume = null;

  @SerializedName("quoteVolume")
  private String quoteVolume = null;

  @SerializedName("openTime")
  private Integer openTime = null;

  @SerializedName("closeTime")
  private Integer closeTime = null;

  @SerializedName("firstId")
  private Integer firstId = null;

  @SerializedName("lastId")
  private Integer lastId = null;

  @SerializedName("count")
  private Integer count = null;

  public Ticker symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(example = "BNBBTC", description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public Ticker priceChange(String priceChange) {
    this.priceChange = priceChange;
    return this;
  }

   /**
   * Get priceChange
   * @return priceChange
  **/
  @Schema(example = "0.17160000", description = "")
  public String getPriceChange() {
    return priceChange;
  }

  public void setPriceChange(String priceChange) {
    this.priceChange = priceChange;
  }

  public Ticker priceChangePercent(String priceChangePercent) {
    this.priceChangePercent = priceChangePercent;
    return this;
  }

   /**
   * Get priceChangePercent
   * @return priceChangePercent
  **/
  @Schema(example = "1.060", description = "")
  public String getPriceChangePercent() {
    return priceChangePercent;
  }

  public void setPriceChangePercent(String priceChangePercent) {
    this.priceChangePercent = priceChangePercent;
  }

  public Ticker prevClosePrice(String prevClosePrice) {
    this.prevClosePrice = prevClosePrice;
    return this;
  }

   /**
   * Get prevClosePrice
   * @return prevClosePrice
  **/
  @Schema(example = "16.35920000", description = "")
  public String getPrevClosePrice() {
    return prevClosePrice;
  }

  public void setPrevClosePrice(String prevClosePrice) {
    this.prevClosePrice = prevClosePrice;
  }

  public Ticker lastPrice(String lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

   /**
   * Get lastPrice
   * @return lastPrice
  **/
  @Schema(example = "27.84000000", description = "")
  public String getLastPrice() {
    return lastPrice;
  }

  public void setLastPrice(String lastPrice) {
    this.lastPrice = lastPrice;
  }

  public Ticker bidPrice(String bidPrice) {
    this.bidPrice = bidPrice;
    return this;
  }

   /**
   * Get bidPrice
   * @return bidPrice
  **/
  @Schema(example = "16.34488284", description = "")
  public String getBidPrice() {
    return bidPrice;
  }

  public void setBidPrice(String bidPrice) {
    this.bidPrice = bidPrice;
  }

  public Ticker bidQty(String bidQty) {
    this.bidQty = bidQty;
    return this;
  }

   /**
   * Get bidQty
   * @return bidQty
  **/
  @Schema(example = "16.34488284", description = "")
  public String getBidQty() {
    return bidQty;
  }

  public void setBidQty(String bidQty) {
    this.bidQty = bidQty;
  }

  public Ticker askPrice(String askPrice) {
    this.askPrice = askPrice;
    return this;
  }

   /**
   * Get askPrice
   * @return askPrice
  **/
  @Schema(example = "16.35920000", description = "")
  public String getAskPrice() {
    return askPrice;
  }

  public void setAskPrice(String askPrice) {
    this.askPrice = askPrice;
  }

  public Ticker askQty(String askQty) {
    this.askQty = askQty;
    return this;
  }

   /**
   * Get askQty
   * @return askQty
  **/
  @Schema(example = "25.06000000", description = "")
  public String getAskQty() {
    return askQty;
  }

  public void setAskQty(String askQty) {
    this.askQty = askQty;
  }

  public Ticker openPrice(String openPrice) {
    this.openPrice = openPrice;
    return this;
  }

   /**
   * Get openPrice
   * @return openPrice
  **/
  @Schema(example = "16.18760000", description = "")
  public String getOpenPrice() {
    return openPrice;
  }

  public void setOpenPrice(String openPrice) {
    this.openPrice = openPrice;
  }

  public Ticker highPrice(String highPrice) {
    this.highPrice = highPrice;
    return this;
  }

   /**
   * Get highPrice
   * @return highPrice
  **/
  @Schema(example = "16.55000000", description = "")
  public String getHighPrice() {
    return highPrice;
  }

  public void setHighPrice(String highPrice) {
    this.highPrice = highPrice;
  }

  public Ticker lowPrice(String lowPrice) {
    this.lowPrice = lowPrice;
    return this;
  }

   /**
   * Get lowPrice
   * @return lowPrice
  **/
  @Schema(example = "16.16940000", description = "")
  public String getLowPrice() {
    return lowPrice;
  }

  public void setLowPrice(String lowPrice) {
    this.lowPrice = lowPrice;
  }

  public Ticker volume(String volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @Schema(example = "1678279.95000000", description = "")
  public String getVolume() {
    return volume;
  }

  public void setVolume(String volume) {
    this.volume = volume;
  }

  public Ticker quoteVolume(String quoteVolume) {
    this.quoteVolume = quoteVolume;
    return this;
  }

   /**
   * Get quoteVolume
   * @return quoteVolume
  **/
  @Schema(example = "27431289.14792300", description = "")
  public String getQuoteVolume() {
    return quoteVolume;
  }

  public void setQuoteVolume(String quoteVolume) {
    this.quoteVolume = quoteVolume;
  }

  public Ticker openTime(Integer openTime) {
    this.openTime = openTime;
    return this;
  }

   /**
   * Get openTime
   * @return openTime
  **/
  @Schema(example = "1592808788637", description = "")
  public Integer getOpenTime() {
    return openTime;
  }

  public void setOpenTime(Integer openTime) {
    this.openTime = openTime;
  }

  public Ticker closeTime(Integer closeTime) {
    this.closeTime = closeTime;
    return this;
  }

   /**
   * Get closeTime
   * @return closeTime
  **/
  @Schema(example = "1592895188637", description = "")
  public Integer getCloseTime() {
    return closeTime;
  }

  public void setCloseTime(Integer closeTime) {
    this.closeTime = closeTime;
  }

  public Ticker firstId(Integer firstId) {
    this.firstId = firstId;
    return this;
  }

   /**
   * Get firstId
   * @return firstId
  **/
  @Schema(example = "62683296", description = "")
  public Integer getFirstId() {
    return firstId;
  }

  public void setFirstId(Integer firstId) {
    this.firstId = firstId;
  }

  public Ticker lastId(Integer lastId) {
    this.lastId = lastId;
    return this;
  }

   /**
   * Get lastId
   * @return lastId
  **/
  @Schema(example = "62739253", description = "")
  public Integer getLastId() {
    return lastId;
  }

  public void setLastId(Integer lastId) {
    this.lastId = lastId;
  }

  public Ticker count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(example = "55958", description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ticker ticker = (Ticker) o;
    return Objects.equals(this.symbol, ticker.symbol) &&
        Objects.equals(this.priceChange, ticker.priceChange) &&
        Objects.equals(this.priceChangePercent, ticker.priceChangePercent) &&
        Objects.equals(this.prevClosePrice, ticker.prevClosePrice) &&
        Objects.equals(this.lastPrice, ticker.lastPrice) &&
        Objects.equals(this.bidPrice, ticker.bidPrice) &&
        Objects.equals(this.bidQty, ticker.bidQty) &&
        Objects.equals(this.askPrice, ticker.askPrice) &&
        Objects.equals(this.askQty, ticker.askQty) &&
        Objects.equals(this.openPrice, ticker.openPrice) &&
        Objects.equals(this.highPrice, ticker.highPrice) &&
        Objects.equals(this.lowPrice, ticker.lowPrice) &&
        Objects.equals(this.volume, ticker.volume) &&
        Objects.equals(this.quoteVolume, ticker.quoteVolume) &&
        Objects.equals(this.openTime, ticker.openTime) &&
        Objects.equals(this.closeTime, ticker.closeTime) &&
        Objects.equals(this.firstId, ticker.firstId) &&
        Objects.equals(this.lastId, ticker.lastId) &&
        Objects.equals(this.count, ticker.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, priceChange, priceChangePercent, prevClosePrice, lastPrice, bidPrice, bidQty, askPrice, askQty, openPrice, highPrice, lowPrice, volume, quoteVolume, openTime, closeTime, firstId, lastId, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ticker {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    priceChange: ").append(toIndentedString(priceChange)).append("\n");
    sb.append("    priceChangePercent: ").append(toIndentedString(priceChangePercent)).append("\n");
    sb.append("    prevClosePrice: ").append(toIndentedString(prevClosePrice)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    bidPrice: ").append(toIndentedString(bidPrice)).append("\n");
    sb.append("    bidQty: ").append(toIndentedString(bidQty)).append("\n");
    sb.append("    askPrice: ").append(toIndentedString(askPrice)).append("\n");
    sb.append("    askQty: ").append(toIndentedString(askQty)).append("\n");
    sb.append("    openPrice: ").append(toIndentedString(openPrice)).append("\n");
    sb.append("    highPrice: ").append(toIndentedString(highPrice)).append("\n");
    sb.append("    lowPrice: ").append(toIndentedString(lowPrice)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    quoteVolume: ").append(toIndentedString(quoteVolume)).append("\n");
    sb.append("    openTime: ").append(toIndentedString(openTime)).append("\n");
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    firstId: ").append(toIndentedString(firstId)).append("\n");
    sb.append("    lastId: ").append(toIndentedString(lastId)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
